require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'eMealia' do
  use_expo_modules!

  pod 'AppCheckCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    # eMealia: patch fmt/base.h (FMT_USE_CONSTEVAL)
    fmt_header = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_header)
      fmt_src = File.read(fmt_header)
      fmt_marker = '// eMealia: force FMT_USE_CONSTEVAL off'
      unless fmt_src.include?(fmt_marker)
        fmt_src = fmt_src.sub(
          "#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval",
          fmt_marker + "\n#undef FMT_USE_CONSTEVAL\n#define FMT_USE_CONSTEVAL 0\n\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
        )
        File.write(fmt_header, fmt_src)
      end
    end


    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_CONSTEVAL='
        end
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

# eMealia: gerar dSYM da Hermes durante o archive
post_integrate do |installer|
  require 'xcodeproj'
  app_project_path = File.join(__dir__, 'eMealia.xcodeproj')
  app_project = Xcodeproj::Project.open(app_project_path)
  main_target = app_project.targets.find { |t| t.name == 'eMealia' }
  if main_target
    hermes_phase_name = 'eMealia: Generate Hermes dSYM'
    already_added = main_target.build_phases.any? { |bp| bp.respond_to?(:name) && bp.name == hermes_phase_name }
    unless already_added
      hermes_phase = main_target.new_shell_script_build_phase(hermes_phase_name)
      hermes_phase.shell_script = [
        'HERMES_FRAMEWORK="${CODESIGNING_FOLDER_PATH}/Frameworks/hermes.framework/hermes"',
        'if [ -f "$HERMES_FRAMEWORK" ] && [ -n "$DWARF_DSYM_FOLDER_PATH" ]; then',
        '  mkdir -p "$DWARF_DSYM_FOLDER_PATH"',
        '  xcrun dsymutil "$HERMES_FRAMEWORK" -o "$DWARF_DSYM_FOLDER_PATH/hermes.framework.dSYM"',
        'fi',
      ].join("\n")
      app_project.save
    end
  end
end
